path: /home/luciano/Documentos/Facultad/4to/2_semestre/ia2-practica/practica_yolo/vehicleDetection/data
train: train/images
val: valid/images

names:
  0: car
  1: threewheel
  2: bus
  3: truck
  4: motorbike
  5: van